version: 2.1
# orbs:
#   slack: circleci/slack@3.4.2

jobs:
  unit:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorpdev/terraform-helm-test:0.1.0
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: bats ./test/unit
  update-helm-charts-index:
    docker:
      - image: docker.mirror.hashicorp.services/circleci/golang:latest
    environment:
      CIRCLE_TAG: v1.1.2 
    steps:
      - checkout
      - run:
          name: verify Chart version matches tag version
          command: |
            GO111MODULE=on go get github.com/mikefarah/yq/v2
            git_tag=$(echo "${CIRCLE_TAG#v}")
            chart_tag=$(yq r Chart.yaml version)
            if [ "${git_tag}" != "${chart_tag}" ]; then
              echo "chart version (${chart_tag}) did not match git version (${git_tag})"
              exit 1
            fi
      - run:
          name: install gh tool
          command: |
            version="2.22.1"
            curl --show-error --silent --location --output "gh.tar.gz" "https://github.com/cli/cli/releases/download/v${version}/gh_${version}_linux_amd64.tar.gz"
            tar -xvzf gh.tar.gz && mkdir -p bin && mv "gh_${version}_linux_amd64/bin/gh" bin/

      - run:
          name: update helm-charts index
          command: |
            export GITHUB_TOKEN="${HELM_CHARTS_GITHUB_TOKEN}"
            ./bin/gh workflow run .github/workflows/publish-charts.yml \
              --repo hashicorp/helm-charts \
              --ref templates_default_test \
              -f SOURCE_TAG="${CIRCLE_TAG}" \
              -f SOURCE_REPO="${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}"
      # - slack/status:
      #     fail_only: true
      #     failure_message: "Failed to trigger an update to the helm charts index. Check the logs at: ${CIRCLE_BUILD_URL}"

workflows:
  version: 2
  test:
    jobs:
      - unit
  update-helm-charts-index:
    jobs:
      - update-helm-charts-index:
          context: helm-charts-trigger-terraform
          # filters:
          #   tags:
          #     only: /^v.*/ # only triggers updating of the helm index on tags
          #   branches:
          #     ignore: /.*/ # don't trigger helm index update on any branch
