# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

{{- if (or (and (ne (.Values.syncWorkspace.enabled | toString) "-") .Values.syncWorkspace.enabled) (and (eq (.Values.syncWorkspace.enabled | toString) "-") .Values.global.enabled)) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "terraform.fullname" . }}-sync-workspace
  labels:
    app: {{ template "terraform.name" . }}
    chart: {{ template "terraform.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}    
{{- end }}