{{- if .Values.CACerts }}
apiVersion: v1
kind: Secret
metadata:
  name: cacert
type: Opaque
data:
  ca_file: |-
    {{ required "CACerts value needs to be set" .Values.CACerts| b64enc | indent 2 }}
{{- end }}
