name: hashicorp/terraform-helm/test
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  unit:
    runs-on: ubuntu-latest
    container:
      image: docker.mirror.hashicorp.services/hashicorpdev/terraform-helm-test:0.1.0
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.0
      - name: Run Unit Tests
        run: bats ./test/unit
