name: update-helm-charts-index
on:
  push:
    tags:
      - "v.*"

permissions:
  contents: read

jobs:
  update-helm-charts-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.0

      - name: verify Chart version matches tag version
        env:
          ref_name: ${{ github.ref_name }}
        run: |-
          chart_tag="$(yq '.version' Chart.yaml)"
          git_tag="${ref_name#v}"
          if [ "${git_tag}" != "${chart_tag}" ]; then
            message="chart version (${chart_tag}) did not match git version (${git_tag})"
            echo "::error title=Version Mismatch::${message}"
            echo "${message}"
            exit 1
          fi

      - name: update helm-charts index
        env:
          GH_TOKEN: ${{ secrets.HELM_CHARTS_GITHUB_TOKEN }}
        run: |-
          ./bin/gh workflow run publish-charts.yml \
            --repo hashicorp/helm-charts \
            --ref main \
            -f SOURCE_TAG="${{ github.ref_name }}" \
            -f SOURCE_REPO="${{ github.repository }}"

      - name: send slack status
        if: failure()
        uses: hashicorp/actions-slack-status@v1
        with:
          status: "failure"
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          failure-message: "Failed to trigger an update to the helm charts index."
